import { Montserrat } from "next/font/google";
import "./globals.css";
import "@/variables/colors.css";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "СТЕНОВЫЕ ECO ПАНЕЛИ / АЛМАТЫ / АСТАНА / БИШКЕК",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={inter.className}>
        <main className="main-wrapper">
            {children}
        </main>
      </body>
    </html>
  );
}





