import HeaderAdditional from "@/components/base/HeaderAdditional";
import "../globals.css";
import Footer from "@/components/base/Footer";
import Anchor from "@/ui/Anchor";

export const metadata = {
  title: "СТЕНОВЫЕ ECO ПАНЕЛИ / АЛМАТЫ / АСТАНА / БИШКЕК",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <main className="layout-additional">
      <HeaderAdditional />
      <article style={{ marginTop: "120px" }}>
        {children}
        <Anchor />
      </article>
      <Footer />
    </main>
  );
}

